feat: ターンを進めていき、先攻後攻表示を切り替える機能の追加  #16
blueteam-recursion/tic-tac-toe pull request #19
Opened 2022-10-24 23:34 UTC by fuji12345

追加点：
Controller内にテーブルオブジェクトを受け取り、ターンを進めていく関数を作成。(changeTurn)
View内に"先行"or"後攻"の文字列を受けとり、画面に描画する関数を作成。(changePlayer)
Table内に現在のターンを受け取り先攻か後攻を返す関数、ターンを進める関数を作成。(firstOrSecond、advanceTurn)

既存のコードを変更しているところがあるので、マージするかどうか相談したいです。
変更点：
View内の関数createInitialBoardの引数をboard(2次元配列)からtable(Tableオブジェクト)に変更しています。 
createInitialBoard内のクリックイベントで呼び出すchangeTurnの引数としてtableを渡すために変更しました。
ターンを保持していく必要があるので、selectGame内で作成した table をゲーム終了まで保持、更新するイメージです。
createInitialBoard内のboardを使っていた部分はtable.boardで変わらず呼び出せます。

元々createInitialBoard(table.borad)で呼び出していたところをcreateInitialBoard(table)にしただけので、大きな問題などはなさそうですが、issue#17との関係があると思うので皆さんの意見も聞きたいです。

2022-10-25 05:30 UTC, Yoppiiii reviewed
確認しました！
個人的には分かりやすくていいと思います！
pimonさんが問題なければマージしていただいて、
それに合わせて＃17の実装をしていきたいと思います！

2022-10-25 06:24 UTC, fuji12345 commented
すいません、コンフリクトしてマージできないと思うので、修正しもう一度プルリクエスト送ります。。

2022-10-25 09:40 UTC, pimon0807 requested changes

2022-10-25 09:40 UTC, pimon0807 commented on main.js
> +    static advanceTurn(turn) {
この関数内ではturnの値が+1されますが、関数終了後は元の値に戻ってしまうと思います。
なので、this.turn += 1のような処理を行い、メンバ変数を上書きしてください！
戻り値に関しては、関数内でturnを上書きするのでなくても問題ないと思います!
View関数内でこの関数の実行後にtableにアクセスすることで更新後のturnを取得できるはずです!

2022-10-25 09:40 UTC, pimon0807 commented on main.js
> +    static changeTurn(table) {
上記でレビューに付随してです。
Table.acvanceTurn();
let currTurn = Table.turn
こうすることでcurrTurnには現在のturnが入力されます!
また,Table.advanceTurnはTableの情報を更新するのみ、Controller.chageTurnはTableに更新の指示とViewに更新後の情報の指示のみとなり、MVCの役割分担がより明確になります!

2022-10-25 09:43 UTC, pimon0807 commented
確認しました。複数の実装お疲れ様でした！
複雑な機能にもかかわらず、ほぼ問題ないと思いました！
ただ、2点修正していただきたい箇所がありますので確認お願いします！
それ以外は要件どうりでよかったです！

2022-10-25 09:45 UTC, pimon0807 commented
createInitialBoard(table.borad)で呼び出していたところをcreateInitialBoard(table)に変更する点は助かりました！
りょうたさんの引数でお願いします!

2022-10-26 05:31 UTC, Yoppiiii commented on main.js
> +    static advanceTurn(turn) {
お疲れ様です！
上記参考に、下記に変更後実装してみましたが、this.turn += 1　の部分が上手くいきません。
static advanceTurn() {
        this.turn += 1;
        console.log(this.turn);
    }

2022-10-26 05:36 UTC, Yoppiiii commented on main.js
> +    static advanceTurn(turn) {
お疲れ様です！
＃17について上記参考に、下記に変更して実装していますが、this.turn += 1　の部分が上手くいかないようです。
私の知識不足かもしれませんが、コンストラクタ内で定義したメンバ変数を更新する方法が見当たりません。
もし方法があればご教授願います！
static advanceTurn() {
        this.turn += 1;
        console.log(this.turn);
    }

2022-10-26 06:06 UTC, fuji12345 commented on main.js
> +    static advanceTurn(turn) {
お疲れ様です！おそらくですがtableインスタンスのthis.turn(table.turn)を変更していくので、
呼び出し方がTable.advaceTurnではなく、table.turnにする必要があると思います！staticメソッドとして呼び出しているので、インスタンスtableの中身は変わっていないということです。分かりにくくてすいません。ググって何かURL貼ります

2022-10-26 06:36 UTC, fuji12345 commented
お疲れ様です。最新のコミットした内容では動作は問題なくいくのですが
 static changeTurn(table) {
        table.advanceTurn();
        let nextTurn = table.turn;
        let player = Table.firstOrSecond(nextTurn);
        View.changePlayer(player);
    }
この関数がコントローラーの役割として合っているのか少し気になります。皆さんの意見を聞きたいです！

2022-10-26 10:29 UTC, pimon0807 commented on main.js
> +    static advanceTurn(turn) {
りょうたさんのおっしゃる通り、static宣言のあるメソッド無いではthiやsurperを使用することができません!
thisやsuperはインスタンスに依存していますが,staticはインスタンスに依存しないメソッドであるためです。

2022-10-26 10:43 UTC, pimon0807 commented
コントローラーの役割として問題ないと思いますよ！
指示役としてtableとViewに指示を出すのみですので！

2022-10-26 10:46 UTC, merged

2022-10-26 13:53 UTC, fuji12345 commented
> コントローラーの役割として問題ないと思いますよ！ 指示役としてtableとViewに指示を出すのみですので！

確認ありがとうございます！
MVCの理解も固まってきたような気がします！

2022-10-26 14:40 UTC, Yoppiiii commented on main.js
> +    static advanceTurn(turn) {
@pimon0807 @fuji12345 
解説していただきありがとうございます！
ようやく腹落ちできました！
static宣言有り　→　thisやsuper使用不可
static宣言無し　→　thisやsuper使用可
この認識ですかね！
ありがとうございます！